SimpleBlog2/Controllers/ArticleCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog2.Models;
using SimpleBlog2.Repositories;

namespace SimpleBlog2.Controllers
{
    public class ArticleCategoryController : Controller
    {
        private readonly IArticleCategoryRepository _articleCategoryRepository;

        public ArticleCategoryController(IArticleCategoryRepository articleCategoryRepository)
        {
            _articleCategoryRepository = articleCategoryRepository;
        }

        // GET: ArticleCategory
        public ActionResult Index()
        {
            return View(_articleCategoryRepository.GetAll());
        }

        // GET: ArticleCategory/Details/5
        public ActionResult Details(int id)
        {
            return View(_articleCategoryRepository.Get(id));
        }

        // GET: ArticleCategory/Create
        public ActionResult Create()
        {
            return View(new ArticleCategoryModel());
        }

        // POST: ArticleCategory/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleCategoryModel articleCategory)
        {
            _articleCategoryRepository.Add(articleCategory);
            return RedirectToAction(nameof(Index));
        }

        // GET: ArticleCategory/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_articleCategoryRepository.Get(id));
        }

        // POST: ArticleCategory/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ArticleCategoryModel articleCategory)
        {
            _articleCategoryRepository.Update(id, articleCategory);
            return RedirectToAction(nameof(Index));
        }

        // GET: ArticleCategory/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_articleCategoryRepository.Get(id));
        }

        // POST: ArticleCategory/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, ArticleCategoryModel articleCategory)
        {
            _articleCategoryRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

SimpleBlog2/Controllers/ArticleCommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog2.Models;
using SimpleBlog2.Repositories;
using SimpleBlog2.ViewModels;

namespace SimpleBlog2.Controllers
{
    public class ArticleCommentController : Controller
    {
        private readonly IArticleCommentRepository _articleCommentRepository;
        private readonly IArticleRepository _articleRepository;

        public ArticleCommentController(IArticleCommentRepository articleCommentRepository, IArticleRepository articleRepository)
        {
            _articleCommentRepository = articleCommentRepository;
            _articleRepository = articleRepository;
        }

        // GET: ArticleComment
        public ActionResult Index()
        {
            var viewModel = new ArticleCommentManageViewModel { ArticleComments = _articleCommentRepository.GetAll().ToList(), Articles = _articleRepository.GetAll().ToList() };
            return View(viewModel);
        }

        // GET: ArticleComment/Details/5
        public ActionResult Details(int id)
        {
            return View(_articleCommentRepository.Get(id));
        }

        // GET: ArticleComment/Create
        public ActionResult Create()
        {
            return View(new ArticleCommentModel());
        }

        //// POST: ArticleComment/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(ArticleCommentModel articleComment)
        //{
        //    _articleCommentRepository.Add(articleComment);
        //    return RedirectToAction("Details", "Article", new { id = articleComment.ArticleId});
        //}

        // POST: ArticleComment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleDetailsViewModel viewModel)
        {
            _articleCommentRepository.Add(viewModel);
            return RedirectToAction("Details", "Article", new { id = viewModel.NewComment.ArticleId });
        }

        // GET: ArticleComment/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_articleCommentRepository.Get(id));
        }

        // POST: ArticleComment/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ArticleCommentModel articleComment)
        {
            _articleCommentRepository.Update(id, articleComment);
            return RedirectToAction(nameof(Index));
        }

        // GET: ArticleComment/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_articleCommentRepository.Get(id));
        }

        // POST: ArticleComment/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, ArticleCommentModel articleComment)
        {
            _articleCommentRepository.Delete(id, articleComment);
            return RedirectToAction(nameof(Index));
        }
    }
}

SimpleBlog2/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog2.Models;
using SimpleBlog2.Repositories;
using SimpleBlog2.ViewModels;

namespace SimpleBlog2.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleRepository _articleRepository;
        private readonly IArticleCategoryRepository _articleCategoryRepository;
        private readonly IArticlePhotoRepository _articlePhotoRepository;
        private readonly IArticleCommentRepository _articleCommentRepository;

        public ArticleController(IArticleRepository articleRepository, IArticleCategoryRepository articleCategoryRepository, IArticlePhotoRepository articlePhotoRepository, IArticleCommentRepository articleCommentRepository)
        {
            _articleRepository = articleRepository;
            _articleCategoryRepository = articleCategoryRepository;
            _articlePhotoRepository = articlePhotoRepository;
            _articleCommentRepository = articleCommentRepository;
        }


        // GET: Article
        public ActionResult Index()
        {
            var viewModel = new ArticleIndexViewModel { Articles = _articleRepository.GetAll().ToList(), ArticlePhotos = _articlePhotoRepository.GetAll().ToList(), ArticleComments = _articleCommentRepository.GetAll().ToList(), ArticleCategories = _articleCategoryRepository.GetAll().ToList() };
            return View(viewModel);
        }

        //GET: ArticleManage
        public ActionResult ArticleManage()
        {
            var viewModel = new ArticleManageViewModel { ArticleList = _articleRepository.GetAll().ToList(), ArticleCategoryList = _articleCategoryRepository.GetAll().ToList() };
            return View(viewModel);
        }

        // GET: Article/Details/5
        public ActionResult Details(int id)
        {
            var viewModel = new ArticleDetailsViewModel { Article = _articleRepository.Get(id), ArticlePhoto = _articlePhotoRepository.GetByArticleId(id), ArticleCategories = _articleCategoryRepository.GetAll().ToList(), ArticleComments = _articleCommentRepository.GetAllForArticle(id).ToList() };
            return View(viewModel);
        }

        // GET: Article/Create
        public ActionResult Create()
        {
            var viewModel = new ArticleCreateViewModel { Article = new ArticleModel(), ArticleCategories = _articleCategoryRepository.GetAll()};
            return View(viewModel);
        }

        // POST: Article/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleCreateViewModel viewModel)
        {
            _articleRepository.Add(viewModel.Article);
            _articlePhotoRepository.Add(viewModel);
            return RedirectToAction(nameof(Index));
        }

        // GET: Article/Edit/5
        public ActionResult Edit(int id)
        {
            var viewModel = new ArticleCreateViewModel { Article = _articleRepository.Get(id), ArticleCategories = _articleCategoryRepository.GetAll(), ArticlePhoto = _articlePhotoRepository.GetByArticleId(id) };
            return View(viewModel);
        }

        // POST: Article/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleCreateViewModel viewModel)
        {
            _articleRepository.Update(viewModel);
            return RedirectToAction(nameof(ArticleManage));
        }

        // GET: Article/Delete/5
        public ActionResult Delete(int id)
        {
            var viewModel = new ArticleCreateViewModel { Article = _articleRepository.Get(id), ArticleCategories = _articleCategoryRepository.GetAll(), ArticlePhoto = _articlePhotoRepository.GetByArticleId(id) };
            return View(viewModel);
        }

        // POST: Article/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, ArticleModel articleModel)
        {
            _articleRepository.Delete(id);
            _articlePhotoRepository.Delete(id);
            _articleCommentRepository.DeleteByArticleId(id);
            return RedirectToAction(nameof(ArticleManage));
        }
    }
}

SimpleBlog2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleBlog2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
            <div class="container body-content" style="margin-left:160px;">
                @RenderBody()
                <footer>
                    <p>
                        &copy; 2020 - SimpleBlog2
                        @Html.ActionLink("Zarządzanie", "ArticleManage", "Article", new { }, new { @class = "h6", style = "padding-left:10px;" })<hr style="margin:0" />
                    </p>
                </footer>
            </div>

            <environment include="Development">
                <script src="~/lib/jquery/dist/jquery.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
                <script src="~/js/site.js" asp-append-version="true"></script>
            </environment>
            <environment exclude="Development">
                <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery"
                        crossorigin="anonymous"
                        integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
                </script>
                <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                        crossorigin="anonymous"
                        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
                </script>
                <script src="~/js/site.min.js" asp-append-version="true"></script>
            </environment>

            @RenderSection("Scripts", required: false)
</body>
</html>

SimpleBlog2/Views/Shared/_LayoutManage.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleBlog2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="sidenav shadow p-3 mb-5 bg-white rounded">
        <h5 style="text-align:center;">Zarządzanie</h5><br /><br />
        @Html.ActionLink("Artykuły", "ArticleManage", "Article", new { }, new { @class = "h6", style = "padding-left:10px;" })<hr style="margin:0" />
        @Html.ActionLink("Kategorie", "Index", "ArticleCategory", new { }, new { @class = "h6", style = "padding-left:10px;" })<hr style="margin:0" />
        @Html.ActionLink("Komentarze", "Index", "ArticleComment", new { }, new { @class = "h6", style = "padding-left:10px;" })<hr style="margin:0" />
        @Html.ActionLink("Blog", "Index", "Article", new { }, new { @class = "h6", style = "padding-left:10px;" })<hr style="margin:0" />
    </div>

    <div class="container body-content" style="margin-left:160px;">
        @RenderBody()
        <footer>
            <p>&copy; 2020 - SimpleBlog2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>